### ISSUE TITLE
Run under python3.5 report - ImportError: No module named 'Queue'

### ISSUE THREAD

**Issue by k870611** [Chetic/robotframework-async#8]
As title says

When I use robotframework-async in python3.5, it report ImportError: No module named 'Queue'

**Comment by alsido** [comment]
If you installed it with pip then you have 1.0.3. The issue seems to be solved in 1.0.4. Just replace the content of `async.py` in `%yourpythoninstallationsfolder%Lib\site-packages\AsyncLibrary` with the content of [the latest version](https://github.com/Chetic/robotframework-async/blob/master/AsyncLibrary/robot_async.py) (_lines 37-40 handle the issue_).
